/** Static Russian UI strings — no i18n framework. */
export const ru = {
  appName: 'Sales OS',

  nav: {
    dashboard: 'Панель',
    tasks: 'Задачи',
    contacts: 'Контакты',
    companies: 'Компании',
    requests: 'Заявки',
    calls: 'Звонки',
    team: 'Команда',
    logout: 'Выйти',
  },

  common: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    saving: 'Сохранение…',
    cancel: 'Отмена',
    edit: 'Изменить',
    delete: 'Удалить',
    email: 'Email',
    phone: 'Телефон',
    name: 'Имя',
    close: 'Закрыть',
    open: 'Открыть',
    back: 'Назад',
    noOrg: 'Нет организации. Завершите регистрацию или попросите приглашение у администратора.',
    saveFailed: 'Не удалось сохранить',
    deleteFailed: 'Не удалось удалить',
    loadFailed: 'Не удалось загрузить данные',
    owner: 'Ответственный',
    noOwner: 'Без ответственного',
    ownerShort: 'Отв.',
  },

  home: {
    tagline: 'CRM для B2B-продаж. Регистрация, команда, контакты и звонки.',
    getStarted: 'Начать',
    signIn: 'Войти',
  },

  login: {
    title: 'Вход',
    subtitle: 'Войдите в рабочее пространство',
    password: 'Пароль',
    submit: 'Войти',
    submitting: 'Вход…',
    error: 'Неверный email или пароль',
    newHere: 'Впервые здесь?',
    createWorkspace: 'Создать пространство',
  },

  register: {
    title: 'Создать пространство',
    subtitle: 'Зарегистрируйте компанию и аккаунт администратора',
    companyName: 'Название компании',
    yourName: 'Ваше имя',
    workEmail: 'Рабочий email',
    passwordHint: 'Пароль (мин. 8 символов)',
    submit: 'Создать',
    submitting: 'Создание…',
    error: 'Не удалось зарегистрироваться',
    hasAccount: 'Уже есть аккаунт?',
    signIn: 'Войти',
  },

  setPassword: {
    title: 'Задайте пароль',
    activateFor: (email: string) => `Активация аккаунта ${email}`,
    activateGeneric: 'Выберите пароль для активации аккаунта',
    passwordHint: 'Пароль (мин. 8 символов)',
    submit: 'Активировать',
    submitting: 'Сохранение…',
    error: 'Не удалось задать пароль',
    invalidLink: 'Недействительная ссылка приглашения.',
    goSignIn: 'Перейти ко входу',
    missingUserId: 'Недействительная ссылка — нет userId',
  },

  dashboard: {
    title: 'Панель',
    welcome: (name: string) => `С возвращением, ${name}.`,
    noOrgInvite: 'Организация не привязана. Попросите администратора отправить приглашение.',
    contacts: 'Контакты',
    calls: 'Звонки',
    team: 'Команда',
    inviteMembers: 'Пригласить коллег',
    completedCalls: 'Завершённые звонки',
    aiSummaryNext: 'AI-сводка — в следующем спринте',
    pilotTitle: 'Подготовка к пилоту',
    pilotSubtitle: 'Пройдите полный путь продажи на одной реальной заявке.',
    pilotCompleted: (completed: number, total: number) => `${completed} из ${total} шагов`,
    pilotLoadFailed: 'Не удалось загрузить прогресс. Обновите страницу.',
    pilotStep: (step: string) =>
      ({
        company: 'Создайте компанию клиента',
        contact: 'Добавьте контакт закупщика',
        request: 'Создайте заявку из сообщения клиента',
        quote: 'Рассчитайте и сформируйте КП',
        sent: 'Скачайте PDF и отметьте отправку',
        outcome: 'Зафиксируйте результат по КП',
      })[step] ?? step,
    pilotNext: 'Следующий шаг',
    pilotContinue: 'Продолжить пилот',
    pilotReady: 'Сценарий пройден. Система готова к сессии обратной связи с менеджером.',
    pilotMetricsTitle: 'Показатели пилота',
    pilotMetricsSubtitle: 'Считаются автоматически по реальным заявкам.',
    pilotSample: (current: number, target: number) =>
      `${current} из ${target} заявок для проверки MVP`,
    pilotRequests: 'Заявки',
    pilotQuotes: 'КП подготовлено',
    pilotSent: 'КП отправлено',
    pilotOutcomes: 'Результат записан',
    pilotQuoteTime: 'Медиана до КП',
    pilotHours: (hours: number) =>
      hours < 1 ? `${Math.max(1, Math.round(hours * 60))} мин` : `${hours.toFixed(1)} ч`,
  },

  contacts: {
    title: 'Контакты',
    subtitle: 'Контакты вашей организации.',
    new: 'Новый контакт',
    edit: 'Изменить контакт',
    search: 'Поиск по имени или email…',
    noCompany: 'Без компании',
    companyFallback: 'Компания',
    notes: 'Заметки',
    addNote: 'Добавить заметку…',
    addNoteBtn: 'Добавить заметку',
    noNotes: 'Заметок пока нет.',
    loadingNotes: 'Загрузка заметок…',
    empty: 'Контактов пока нет.',
    deleteConfirm: 'Удалить этот контакт?',
    loadError: 'Не удалось загрузить контакты',
    noteSaveError: 'Не удалось сохранить заметку',
    notesLoadError: 'Не удалось загрузить заметки',
  },

  companies: {
    title: 'Компании',
    new: 'Новая компания',
    edit: 'Изменить компанию',
    search: 'Поиск по названию, ИНН или email…',
    companyName: 'Название компании',
    inn: 'ИНН (10 или 12 цифр)',
    website: 'Сайт',
    noDetails: 'Нет данных',
    empty: 'Компаний пока нет',
    deleteConfirm: 'Удалить эту компанию?',
    loadError: 'Не удалось загрузить компании',
    country: 'Страна',
    countryRU: 'Россия',
    countryUZ: 'Узбекистан',
    countryKZ: 'Казахстан',
    countryKG: 'Киргизия',
    taxIdRU: 'ИНН (10 или 12 цифр)',
    taxIdUZ: 'СТИР (9 цифр)',
    taxIdKZ: 'БИН/ИИН (12 цифр)',
    taxIdKG: 'ИНН (14 цифр)',
    fillByInn: 'Заполнить по ИНН',
    innLooking: 'Ищем в ЕГРЮЛ…',
    innNeedValid: 'Введите ИНН из 10 или 12 цифр',
    innNotConfigured: 'Автозаполнение не настроено: добавьте DADATA_API_KEY в переменные API-сервиса',
    innNotFound: 'В ЕГРЮЛ не найдено',
    innLookupError: 'Не удалось получить данные по ИНН',
  },

  calls: {
    title: 'Звонки',
    subtitle: 'Журнал звонков с контактами.',
    logCall: 'Записать звонок',
    logCallTitle: 'Новый звонок',
    selectContact: 'Выберите контакт',
    outbound: 'Исходящий',
    inbound: 'Входящий',
    startCall: 'Начать звонок',
    complete: 'Завершить',
    missed: 'Пропущен',
    empty: 'Звонков пока нет.',
    addContactFirst: 'Сначала добавьте контакт, чтобы записывать звонки.',
    noOrg: 'Нет контекста организации.',
    loadError: 'Не удалось загрузить звонки',
    logError: 'Не удалось записать звонок',
    completeError: 'Не удалось завершить звонок',
    missError: 'Не удалось отметить пропущенным',
  },

  requests: {
    title: 'Заявки',
    subtitle: 'Заявки на металлопрокат.',
    new: 'Новая заявка',
    empty: 'Заявок пока нет.',
    untitled: 'Без названия',
    lines: (n: number) => `${n} поз.`,
    loadError: 'Не удалось загрузить заявки',
    newTitle: 'Новая заявка',
    back: '← К заявкам',
    manual: 'Вручную',
    fromMessage: 'Из письма / чата',
    pasteLabel: 'Вставьте письмо или сообщение клиента целиком',
    pastePlaceholder:
      'Например:\nДобрый день! Нужны:\n1. Лист 5х1500х6000 09Г2С — 10 т\n2. Труба 57х3,5 Ст20 — 200 м',
    parseText: 'Распознать позиции',
    uploadLabel: 'Или загрузите файл TXT / CSV / XLSX / PDF',
    sourceFile: 'Исходный файл',
    parsedWith: (p: string) =>
      p === 'e-metall'
        ? 'Позиции распознаны через E‑Metall.'
        : 'Позиции распознаны встроенным разбором.',
    reviewRequired: 'Проверьте каждую позицию перед сохранением.',
    recognitionConfidence: (value: number) => `Распознано: ${value}%`,
    reviewWarning: (field: string) =>
      `Проверьте: ${
        ({
          productType: 'вид продукции',
          steelGrade: 'марку стали',
          dimensions: 'размеры',
          quantity: 'количество',
          unit: 'единицу измерения',
        } as Record<string, string>)[field] ?? field
      }`,
    titleField: 'Название',
    contactOptional: 'Контакт (необязательно)',
    notes: 'Примечания',
    lineItems: 'Позиции',
    addLine: '+ Добавить позицию',
    removeLine: 'Удалить позицию',
    rawLine: 'Исходная строка',
    productType: 'Вид продукции',
    steelGrade: 'Марка стали',
    gost: 'ГОСТ',
    dimensions: 'Размеры',
    thickness: 'Толщина',
    qty: 'Кол-во',
    unit: 'Ед. изм.',
    saveRequest: 'Сохранить заявку',
    parseFailed: 'Не удалось разобрать',
    fileParseFailed: 'Не удалось разобрать файл',
    linesRequired: 'Добавьте хотя бы одну позицию.',
    sourceLabel: (source: string) =>
      ({
        MANUAL: 'вручную',
        PASTED: 'из письма / чата',
        FILE: 'из файла',
      })[source] ?? source,
    originalMessage: 'Исходное письмо / сообщение',
    detailTitle: 'Заявка',
    status: 'Статус',
    positions: 'Позиции',
    searchEmetall: 'Поиск в E-Metall',
    searching: 'Поиск…',
    offers: 'Предложения',
    inStock: 'в наличии',
    searchDoneEmpty:
      'Поиск завершён (E-Metall не настроен или предложений нет). Подключите API-ключи для живых результатов.',
    notFound: 'Заявка не найдена',
    searchFailed: 'Поиск не удался',
    quoted: 'КП готово',
    sent: 'КП отправлено',
    positionsAndPrices: 'Позиции и коммерческий расчёт',
    purchaseAmount: 'Закупка, сумма',
    saleAmount: 'Продажа, сумма',
    priceImport: 'Загрузить расчёт из XLSX/CSV',
    priceImportHint:
      'Колонки: «Наименование», «Закупочная цена за единицу» и необязательно «Цена продажи за единицу». Система сопоставляет наименования и умножает цену на количество из заявки.',
    priceImporting: 'Загружаем…',
    priceImportApplied: (fileName: string, count: number) =>
      `Загружено из «${fileName}»: ${count} строк. Проверьте соответствие позиций и суммы.`,
    priceImportMismatch: (applied: number, imported: number, requested: number) =>
      `Совпало по наименованию ${applied} из ${requested} позиций заявки; в файле ${imported} строк. Несовпавшие цены не применены.`,
    priceImportMissingQuantity: (count: number) =>
      `Для ${count} позиций не распознано положительное количество — цены не применены.`,
    priceImportFailed: 'Не удалось загрузить прайс. Проверьте заголовки и формат XLSX/CSV.',
    calculation: 'Расчёт прибыли',
    sellerName: 'Поставщик в КП',
    deliveryTerms: 'Условия поставки',
    logisticsCost: 'Логистика',
    otherCosts: 'Прочие расходы',
    validityDays: 'Срок действия КП, дней',
    followUpAt: 'Следующий контакт',
    purchaseTotal: 'Закупка',
    saleTotal: 'Продажа',
    profit: 'Прибыль',
    margin: 'Маржа',
    prepareQuote: 'Сформировать КП и поставить задачу',
    preparingQuote: 'Формируем КП…',
    followUpHint: 'После формирования система автоматически создаст задачу на выбранную дату.',
    quoteEveryLine: 'Заполните сумму закупки и продажи по каждой позиции.',
    quoteInvalidAmount: 'Введите корректные неотрицательные суммы. Буквы и отрицательные значения недопустимы.',
    quoteInvalidValidity: 'Срок действия КП должен быть целым числом от 1 до 90 дней.',
    quoteFollowUpFuture: 'Дата следующего контакта должна быть в будущем.',
    quoteFailed: 'Не удалось сформировать КП',
    openProposal: 'Открыть КП',
    downloadProposal: 'Скачать PDF',
    downloadingProposal: 'Готовим PDF…',
    downloadProposalFailed: 'Не удалось скачать PDF. Используйте печать как запасной вариант.',
    downloadTrackFailed: 'PDF скачан, но не удалось записать это действие в хронологию.',
    sentVia: 'Канал отправки',
    sentViaEmail: 'Email',
    sentViaTelegram: 'Telegram',
    sentViaWhatsapp: 'WhatsApp',
    sentViaMax: 'MAX',
    sentViaManual: 'Другой канал',
    sentTo: 'Адресат: e-mail, телефон или аккаунт',
    sentToRequired: 'Укажите адресата для выбранного канала отправки.',
    markSent: 'Отметить отправленным',
    markingSent: 'Сохраняем…',
    markSentFailed: 'Не удалось отметить КП отправленным.',
    sentViaLabel: (channel: string) =>
      ({
        EMAIL: 'Email',
        TELEGRAM: 'Telegram',
        WHATSAPP: 'WhatsApp',
        MAX: 'MAX',
        MANUAL: 'Другой канал',
      })[channel] ?? channel,
    sentAt: (date: string, channel: string, recipient?: string | null) =>
      `Отправлено ${date} · ${channel}${recipient ? ` · ${recipient}` : ''}`,
    followUpFilters: 'Фильтр следующих контактов',
    followUpAll: 'Все',
    followUpOverdue: 'Просрочено',
    followUpToday: 'Сегодня',
    followUpUpcoming: 'Предстоящие',
    followUpEmpty: 'В этой очереди нет заявок.',
    followUpOverdueAt: (date: string) => `Контакт просрочен · ${date}`,
    followUpTodayAt: (time: string) => `Связаться сегодня · ${time}`,
    followUpUpcomingAt: (date: string) => `Следующий контакт · ${date}`,
    followUpAction: 'Связаться',
    activityTitle: 'Хронология заявки',
    activityLabel: (type: string) =>
      ({
        REQUEST_CREATED: 'Заявка создана',
        QUOTE_PREPARED: 'КП подготовлено',
        FOLLOW_UP_SCHEDULED: 'Следующий контакт назначен',
        PROPOSAL_DOWNLOADED: 'PDF скачан',
        PROPOSAL_SENT: 'КП отправлено',
        OUTCOME_RECORDED: 'Результат зафиксирован',
      })[type] ?? type,
    activityDetails: (type: string, details: Record<string, string>) => {
      if (type === 'FOLLOW_UP_SCHEDULED' && details.followUpAt) {
        return `Контакт: ${new Intl.DateTimeFormat('ru-RU', {
          dateStyle: 'short',
          timeStyle: 'short',
        }).format(new Date(details.followUpAt))}`;
      }
      if (type === 'QUOTE_PREPARED' && details.priceSourceFileName) {
        return `Источник закупочных цен: ${details.priceSourceFileName}`;
      }
      if (type === 'PROPOSAL_SENT' && details.sentVia) {
        return `Канал: ${
          ({
            EMAIL: 'Email',
            TELEGRAM: 'Telegram',
            WHATSAPP: 'WhatsApp',
            MAX: 'MAX',
            MANUAL: 'Другой',
          })[details.sentVia] ?? details.sentVia
        }${details.sentTo ? ` · Адресат: ${details.sentTo}` : ''}`;
      }
      if (type === 'OUTCOME_RECORDED' && details.outcome) {
        return (
          {
            WON: 'Заказ получен',
            LOST: 'Проиграно',
            NO_RESPONSE: 'Нет ответа',
          }[details.outcome] ?? details.outcome
        );
      }
      return '';
    },
    outcomeTitle: 'Результат по КП',
    outcomeWon: 'Заказ получен',
    outcomeLost: 'Проиграно',
    outcomeNoResponse: 'Нет ответа',
    outcomeReason: 'Причина / комментарий',
    outcomeReasonRequired: 'Укажите причину или комментарий.',
    saveOutcome: 'Зафиксировать',
    outcomeFailed: 'Не удалось сохранить результат.',
    outcomeLabel: (outcome: string) =>
      ({
        WON: 'Заказ получен',
        LOST: 'Проиграно',
        NO_RESPONSE: 'Нет ответа',
      })[outcome] ?? outcome,
    printProposal: 'Печать',
    proposalNotReady: 'Сначала выполните расчёт и сформируйте КП.',
  },

  tasks: {
    title: 'Задачи',
    subtitle: 'Ни одного клиента без следующего шага.',
    today: 'Сегодня',
    todayEmpty: 'На сегодня задач нет — отличная работа!',
    all: 'Открытые задачи',
    new: 'Новая задача',
    edit: 'Изменить задачу',
    titleField: 'Что сделать (например: Позвонить по КП)',
    due: 'Срок',
    type: 'Тип',
    typeCall: 'Звонок',
    typeMessage: 'Написать',
    typeMeeting: 'Встреча',
    typeTodo: 'Задача',
    forContact: 'Контакт (необязательно)',
    forCompany: 'Компания (необязательно)',
    assignee: 'Исполнитель',
    me: 'Я',
    done: 'Выполнено',
    cancelTask: 'Отменить',
    overdue: 'просрочено',
    empty: 'Открытых задач нет.',
    loadError: 'Не удалось загрузить задачи',
    cancelConfirm: 'Отменить эту задачу?',
  },

  team: {
    title: 'Команда',
    subtitle: 'Пригласите коллег в рабочее пространство.',
    inviteTitle: 'Пригласить участника',
    sendInvite: 'Отправить приглашение',
    inviting: 'Отправка…',
    shareLink: 'Ссылка для активации:',
    empty: 'Участников пока нет.',
    loadError: 'Не удалось загрузить команду',
    inviteError: 'Не удалось отправить приглашение',
    noOrg: 'Нет контекста организации',
  },
} as const;
