/** Static Russian UI strings — no i18n framework. */
export const ru = {
  appName: 'Sales OS',

  nav: {
    dashboard: 'Панель',
    contacts: 'Контакты',
    companies: 'Компании',
    requests: 'Заявки',
    calls: 'Звонки',
    team: 'Команда',
    logout: 'Выйти',
  },

  common: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    saving: 'Сохранение…',
    cancel: 'Отмена',
    edit: 'Изменить',
    delete: 'Удалить',
    email: 'Email',
    phone: 'Телефон',
    name: 'Имя',
    close: 'Закрыть',
    open: 'Открыть',
    back: 'Назад',
    noOrg: 'Нет организации. Завершите регистрацию или попросите приглашение у администратора.',
    saveFailed: 'Не удалось сохранить',
    deleteFailed: 'Не удалось удалить',
    loadFailed: 'Не удалось загрузить данные',
    owner: 'Ответственный',
    noOwner: 'Без ответственного',
    ownerShort: 'Отв.',
  },

  home: {
    tagline: 'CRM для B2B-продаж. Регистрация, команда, контакты и звонки.',
    getStarted: 'Начать',
    signIn: 'Войти',
  },

  login: {
    title: 'Вход',
    subtitle: 'Войдите в рабочее пространство',
    password: 'Пароль',
    submit: 'Войти',
    submitting: 'Вход…',
    error: 'Неверный email или пароль',
    newHere: 'Впервые здесь?',
    createWorkspace: 'Создать пространство',
  },

  register: {
    title: 'Создать пространство',
    subtitle: 'Зарегистрируйте компанию и аккаунт администратора',
    companyName: 'Название компании',
    yourName: 'Ваше имя',
    workEmail: 'Рабочий email',
    passwordHint: 'Пароль (мин. 8 символов)',
    submit: 'Создать',
    submitting: 'Создание…',
    error: 'Не удалось зарегистрироваться',
    hasAccount: 'Уже есть аккаунт?',
    signIn: 'Войти',
  },

  setPassword: {
    title: 'Задайте пароль',
    activateFor: (email: string) => `Активация аккаунта ${email}`,
    activateGeneric: 'Выберите пароль для активации аккаунта',
    passwordHint: 'Пароль (мин. 8 символов)',
    submit: 'Активировать',
    submitting: 'Сохранение…',
    error: 'Не удалось задать пароль',
    invalidLink: 'Недействительная ссылка приглашения.',
    goSignIn: 'Перейти ко входу',
    missingUserId: 'Недействительная ссылка — нет userId',
  },

  dashboard: {
    title: 'Панель',
    welcome: (name: string) => `С возвращением, ${name}.`,
    noOrgInvite: 'Организация не привязана. Попросите администратора отправить приглашение.',
    contacts: 'Контакты',
    calls: 'Звонки',
    team: 'Команда',
    inviteMembers: 'Пригласить коллег',
    completedCalls: 'Завершённые звонки',
    aiSummaryNext: 'AI-сводка — в следующем спринте',
  },

  contacts: {
    title: 'Контакты',
    subtitle: 'Контакты вашей организации.',
    new: 'Новый контакт',
    edit: 'Изменить контакт',
    search: 'Поиск по имени или email…',
    noCompany: 'Без компании',
    companyFallback: 'Компания',
    notes: 'Заметки',
    addNote: 'Добавить заметку…',
    addNoteBtn: 'Добавить заметку',
    noNotes: 'Заметок пока нет.',
    loadingNotes: 'Загрузка заметок…',
    empty: 'Контактов пока нет.',
    deleteConfirm: 'Удалить этот контакт?',
    loadError: 'Не удалось загрузить контакты',
    noteSaveError: 'Не удалось сохранить заметку',
    notesLoadError: 'Не удалось загрузить заметки',
  },

  companies: {
    title: 'Компании',
    new: 'Новая компания',
    edit: 'Изменить компанию',
    search: 'Поиск по названию, ИНН или email…',
    companyName: 'Название компании',
    inn: 'ИНН (10 или 12 цифр)',
    website: 'Сайт',
    noDetails: 'Нет данных',
    empty: 'Компаний пока нет',
    deleteConfirm: 'Удалить эту компанию?',
    loadError: 'Не удалось загрузить компании',
  },

  calls: {
    title: 'Звонки',
    subtitle: 'Журнал звонков с контактами.',
    logCall: 'Записать звонок',
    logCallTitle: 'Новый звонок',
    selectContact: 'Выберите контакт',
    outbound: 'Исходящий',
    inbound: 'Входящий',
    startCall: 'Начать звонок',
    complete: 'Завершить',
    missed: 'Пропущен',
    empty: 'Звонков пока нет.',
    addContactFirst: 'Сначала добавьте контакт, чтобы записывать звонки.',
    noOrg: 'Нет контекста организации.',
    loadError: 'Не удалось загрузить звонки',
    logError: 'Не удалось записать звонок',
    completeError: 'Не удалось завершить звонок',
    missError: 'Не удалось отметить пропущенным',
  },

  requests: {
    title: 'Заявки',
    subtitle: 'Заявки на металлопрокат.',
    new: 'Новая заявка',
    empty: 'Заявок пока нет.',
    untitled: 'Без названия',
    lines: (n: number) => `${n} поз.`,
    loadError: 'Не удалось загрузить заявки',
    newTitle: 'Новая заявка',
    back: '← К заявкам',
    manual: 'Вручную',
    upload: 'Загрузка / вставка',
    pasteLabel: 'Вставьте текст',
    pastePlaceholder: 'Вставьте текст заявки…',
    parseText: 'Разобрать текст',
    uploadLabel: 'Или загрузите файл / фото',
    parsedWith: (p: string) => `Разобрано: ${p} — проверьте позиции перед сохранением.`,
    titleField: 'Название',
    contactOptional: 'Контакт (необязательно)',
    notes: 'Примечания',
    lineItems: 'Позиции',
    addLine: '+ Добавить позицию',
    rawLine: 'Строка / описание',
    steelGrade: 'Марка стали',
    gost: 'ГОСТ',
    thickness: 'Толщина',
    qty: 'Кол-во',
    saveRequest: 'Сохранить заявку',
    parseFailed: 'Не удалось разобрать',
    fileParseFailed: 'Не удалось разобрать файл',
    detailTitle: 'Заявка',
    status: 'Статус',
    positions: 'Позиции',
    searchEmetall: 'Поиск в E-Metall',
    searching: 'Поиск…',
    offers: 'Предложения',
    inStock: 'в наличии',
    searchDoneEmpty:
      'Поиск завершён (E-Metall не настроен или предложений нет). Подключите API-ключи для живых результатов.',
    notFound: 'Заявка не найдена',
    searchFailed: 'Поиск не удался',
  },

  team: {
    title: 'Команда',
    subtitle: 'Пригласите коллег в рабочее пространство.',
    inviteTitle: 'Пригласить участника',
    sendInvite: 'Отправить приглашение',
    inviting: 'Отправка…',
    shareLink: 'Ссылка для активации:',
    empty: 'Участников пока нет.',
    loadError: 'Не удалось загрузить команду',
    inviteError: 'Не удалось отправить приглашение',
    noOrg: 'Нет контекста организации',
  },
} as const;
